#ifndef MY_VERSION
#define MY_VERSION	"5.0"
#endif

#define PROGRAM_NAME	"muscle"

////////////////////
// Commands
#define C(x)	STR_OPT(x)
#include "cmds.h"
////////////////////

STR_OPT(log)
STR_OPT(output)
STR_OPT(output1)
STR_OPT(output2)
STR_OPT(input2)
STR_OPT(joinprefix)
STR_OPT(joinpaths)
STR_OPT(linkage)
STR_OPT(joins)
STR_OPT(tsvout)
STR_OPT(guidetreein)
STR_OPT(guidetreeout)
STR_OPT(prefix)
STR_OPT(nodes)
STR_OPT(label)
STR_OPT(savedir)
STR_OPT(db)
STR_OPT(label1)
STR_OPT(label2)
STR_OPT(subtreeout)
STR_OPT(supertreeout)
STR_OPT(refmsa)
STR_OPT(ref)
STR_OPT(refdir)
STR_OPT(testdir)
STR_OPT(testdir1);
STR_OPT(testdir2);
STR_OPT(outdir)
STR_OPT(hmmin)
STR_OPT(hmmout)
STR_OPT(report)
STR_OPT(accalnout)
STR_OPT(perm)

UNS_OPT(threads)
UNS_OPT(consiters)
UNS_OPT(refineiters)
UNS_OPT(randseed)
UNS_OPT(paircount)
UNS_OPT(n)
UNS_OPT(splitcount)
UNS_OPT(maxcoarse)
UNS_OPT(perturb)

FLT_OPT(min_cons_pct)
FLT_OPT(max_gap_fract)
FLT_OPT(minea)
FLT_OPT(pctid)

FLAG_OPT(quiet)
FLAG_OPT(compilerinfo)
FLAG_OPT(right)
FLAG_OPT(scaledist)
FLAG_OPT(eadist)
FLAG_OPT(force_super4)
FLAG_OPT(force_probcons)
FLAG_OPT(allpairs)
FLAG_OPT(allperms)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  MUSCLE opts 
FLAG_OPT(le)
FLAG_OPT(sp)
FLAG_OPT(sv)
FLAG_OPT(spn)
FLAG_OPT(core)
FLAG_OPT(nocore)
FLAG_OPT(diags1)
FLAG_OPT(diags2)
FLAG_OPT(diags)
FLAG_OPT(msf)
FLAG_OPT(verbose)
FLAG_OPT(anchors)
FLAG_OPT(noanchors)
FLAG_OPT(refine)
FLAG_OPT(refinew)
FLAG_OPT(sw)
FLAG_OPT(profile)
FLAG_OPT(ppscore)
FLAG_OPT(clusteronly)
FLAG_OPT(brenner)
FLAG_OPT(dimer)
FLAG_OPT(clw)
FLAG_OPT(clwstrict)
FLAG_OPT(html)
FLAG_OPT(version)
FLAG_OPT(stable)
FLAG_OPT(group)
FLAG_OPT(fasta)
FLAG_OPT(profdb)
FLAG_OPT(phyi)
FLAG_OPT(phys)
FLAG_OPT(tomhydro)
FLAG_OPT(maketree)
FLAG_OPT(accs)

STR_OPT(in)
STR_OPT(in1)
STR_OPT(in2)
STR_OPT(pairs)
STR_OPT(out)
STR_OPT(maxiters)
STR_OPT(maxhours)
STR_OPT(gapopen)
STR_OPT(gapopen2)
STR_OPT(gapextend)
STR_OPT(gapextend2)
STR_OPT(gapambig)
STR_OPT(center)
STR_OPT(smoothscoreceil)
STR_OPT(minbestcolscore)
STR_OPT(minsmoothscore)
STR_OPT(objscore)
STR_OPT(smoothwindow)
STR_OPT(refinewindow)
STR_OPT(fromwindow)
STR_OPT(towindow)
STR_OPT(savewindow)
STR_OPT(windowoffset)
STR_OPT(firstwindow)
STR_OPT(anchorspacing)
STR_OPT(loga)
STR_OPT(maxtrees)
STR_OPT(sueff)
STR_OPT(distance)
STR_OPT(distance1)
STR_OPT(distance2)
STR_OPT(weight)
STR_OPT(weight1)
STR_OPT(weight2)
STR_OPT(cluster)
STR_OPT(cluster1)
STR_OPT(cluster2)
STR_OPT(root1)
STR_OPT(root2)
STR_OPT(tree1)
STR_OPT(tree2)
STR_OPT(usetree)
STR_OPT(usetree_nowarn)
STR_OPT(diaglength)
STR_OPT(diagmargin)
STR_OPT(diagbreak)
STR_OPT(hydro)
STR_OPT(hydrofactor)
STR_OPT(spscore)
STR_OPT(seqtype)
STR_OPT(maxmb)
STR_OPT(computeweights)
STR_OPT(maxsubfam)
STR_OPT(scorefile)
STR_OPT(termgaps)
STR_OPT(fastaout)
STR_OPT(clwout)
STR_OPT(clwstrictout)
STR_OPT(htmlout)
STR_OPT(msfout)
STR_OPT(phyiout)
STR_OPT(physout)
STR_OPT(matrix)
STR_OPT(distmx1)
STR_OPT(distmx2)

#undef FLAG_OPT
#undef UNS_OPT
#undef FLT_OPT
#undef STR_OPT
