name: build_linux

on:
  # Enable manual run from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build-commands
        with:
          arch: aarch64
          run: |
            echo Starting Build-commands
            echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
            uname -a
            cd $GITHUB_WORKSPACE
            ls -lh
            cd src
            make LDFLAGS2=-static
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: muscle-linux-aarch64-binary
          path: src/Linux/muscle
